Added environment resolving for wa

diff --git a/WA/Dockerfile b/WA/Dockerfile
--- a/WA/Dockerfile
+++ b/WA/Dockerfile
@@ -1,8 +1,13 @@
 ARG DOTNET_SDK_VERSION=10.0
+ARG ENVIRONMENT
 
 # ===== Build stage =====
 FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_VERSION} AS build
 WORKDIR .
+
+ARG ENVIRONMENT
+RUN test -n "$ENVIRONMENT" || (echo "❌ ENVIRONMENT build-arg is required, try running with --build-arg ENVIRONMENT=Development OR add it to your build args" && exit 1)
+RUN echo "🔧 Building for environment: $ENVIRONMENT"
 
 # copy csproj first (sneller cachen)
 COPY WA/WA.csproj WA/
@@ -12,8 +17,12 @@ RUN dotnet restore WA/WA.csproj
 # copy rest
 COPY WA/ WA/
 COPY SharedLibrary/ SharedLibrary/
+RUN dotnet publish WA/WA.csproj \
+    -c Release \
+    -p:EnvironmentName=${ENVIRONMENT} \
+    -o /app/out
 
-RUN dotnet publish WA/WA.csproj -c Release -o /app/out
+RUN ls -R /app/out/wwwroot
 
 # ===== Runtime stage =====
 FROM nginx:alpine
